server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: MRL-Register
  security: #开启eureka服务端端点保护，访问eureka服务的受保护资源需要用户密码，defaultZone也需要加上user:pwd@
    user:
      name: mrl
      password: luc
  boot: #配置客户端访问的服务端地址及用户密码
    admin:
      client:
        url: http://localhost:8401
        username: mrl
        password: luc

info: #配置SBA客户端的名称、描述、版本
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*' #将客户端所有监控端点都暴露给SBA服务端
  endpoint:
    health:
      show-details: always #总是展示详细的健康信息

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server，默认为true
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true，由于当前是单点Eureka Server，不需要同步其他的Eureka Server注册数据
    instance-info-replication-interval-seconds: 30 #微服务启动过30s注册到服务中心
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/